server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: postgres
    password: test1234
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: orderdb
  jpa:
    # database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296

### Configured in config server
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


