server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: postgres
    password: test1234
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: productdb
  jpa:
    # database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update


